### PR TITLE
Cookies saving token instead of id

### PR DESCRIPTION
**Pull request by JakobTolkemit**
Before, the cookie stored the id of the wishlist, but that's not very secure. 
A visitor could just guess numbers, setting the value of the cookie, until he finds a wishlist of another customer and mess with it.

So now, instead of storing the id, the cookie stores a random 50 character long token which gets associated with the wishlist.

### CODE REVIEW

**Comment by bitbager** [comment]
Thanks! Could you please fix the build?

**Comment by JakobTolkemit** [comment]
It seems that Symfony notifications don't trigger when the "MOCKSESSID" cookie is not set.

**Comment by JakobTolkemit** [comment]
Also could you rerun the build? It seems to have failed because of a server being down.

**Comment by bitbager** [comment]
Thanks a lot!

**Pull request merged**
