### PR TITLE
Update MergeUserWishlistItemsListener.php

### PR DESCRIPTION
**Pull request by pogorivan**
Without this change I have an error while login with empty wishlist

### CODE REVIEW

**Comment by bitbager** [comment]
Can I ask you to fix the build? 🙂

**Comment by pogorivan** [comment]
Fixed the part, related to my edit. But I am not familiar with Behat and don't know how to fix notification issue

**Comment by bitbager** [comment]
Thank you. We will fix it in the incoming days.

CC @patrick477

**Comment by bitbager** [comment]
CC @patrick477

**Pull request merged**
