### PR TITLE
Update controller actions services declaration

### PR DESCRIPTION
**Pull request by kayneth**
Hi all ! 

There's an error on SF 4+ due to the fact that the services are all private by default.

### CODE REVIEW

**Comment by pogorivan** [comment]
Hello! Can anyone merge it? Thanks

**Comment by bitbager** [comment]
Can I ask you to update it to follow the `- { name: tag_name }` notation?

**Comment by kayneth** [comment]
Hi ! 
I didn't see the notification before. 
I updated the PR with your request. 
I was forced to update dev requirements for sylius 1.3.

**Comment by bitbager** [comment]
Thanks a lot!

**Pull request merged**
